exclude: ^uploads/

# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            # Add any types required by your project here
            "types-Pillow",
            "types-toml",
        ]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use a recent stable version
    hooks:
    -   id: prettier
        types: [file]
        files: '^front/app/.*\.(js|jsx|ts|tsx|css|html|json|yaml|yml|md)$' # Target files within front/app
        args: [--write]
        description: 'Format frontend files with Prettier.'

# -   repo: local
#     hooks:
#     -   id: eslint
#         name: eslint (front/app)
#         entry: bash -c 'cd front/app && npm install --prefix . && npm run lint'
#         language: system
#         types: [file]
#         files: '^front/app/.*\.(js|jsx|ts|tsx)$'
#         pass_filenames: false
#         always_run: true
#         verbose: true
#         require_serial: true # Ensure npm install completes before running lint
